name: Autonomo y Deploy FTP
on:
  push:
    paths:
      - 'database.json'
      - 'index.html'
      - 'builder.py'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: ğŸ¤– Generar ManresIA
        run: python builder.py

      - name: ğŸ“¤ Pujar al Hosting (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
         server-dir: public_html/
          # posa-la aquÃ­ sota. Si no, puja a l'arrel.
          server-dir: ./
